name: Bandit Scan

on:
  push:
    branches:
      - master  # Adjust to the branch you want to trigger the scan on

jobs:
  image_scan:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Docker
        uses: actions/setup-docker@v2
        with:
          docker-version: '20.10.7'
  
      - name: Build Docker Image
        run: docker build -t myapp:latest .
  
      - name: Docker Scout Scan
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock shiftleft/scout-cli:latest test myapp:latest
