name: Bandit Scan

on:
  push:
    branches:
      - master  # Adjust to the branch you want to trigger the scan on

jobs:

  owasp_dependency_check:
    name: Run Dependency Scan
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run OWASP Dependency Check
      run: |
        # Install OWASP Dependency Check
        VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
        curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
        unzip dependency-check.zip
        # chmod +x dependency-check/bin/dependency-check.sh

        # Run OWASP Dependency Check and generate JSON report
        dependency-check/bin/dependency-check.sh --scan ../../

  
