name: Bandit Scan

on:
  push:
    branches:
      - master  # Adjust to the branch you want to trigger the scan on

jobs:

  owasp_dependency_check:
    name: Run Dependency Scan
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Run OWASP Dependency Check
      run: |
        pip install safety
        safety check -r requirements.txt --output json > sca_report.json
        ls
        pwd

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: safety-check-findings
        path: sca-report.json
