name: Bandit Scan

on:
  push:
    branches:
      - master  # Adjust to the branch you want to trigger the scan on

jobs:
  image_scan:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'
  
      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .
  
      - name: Docker Scout Scan
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock docker/scout-cli test myapp:latest
