name: Bandit Scan

on:
  push:
    branches:
      - master  # Adjust to the branch you want to trigger the scan on

jobs:
  security_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you need

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-reports.json
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      if: always() # run even if previous failed
      with:
        name: bandit-findings
        path: bandit-reports.json
